<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>io.servicecomb.poc.demo</groupId>
  <artifactId>seckill</artifactId>
  <packaging>pom</packaging>
  <version>0.2.0-SNAPSHOT</version>

  <modules>
    <module>library/seckill-event-store</module>
    <module>library/seckill-infra-redis</module>
    <module>library/seckill-infra-kafka</module>
    <module>library/seckill-infra-es</module>
    <module>service/seckill-command-service</module>
    <module>service/seckill-persist-service</module>
    <module>service/seckill-admin-service</module>
    <module>service/seckill-query-service</module>
    <module>service/seckill-event-service</module>
    <module>service/seckill-gateway</module>
    <module>test/test-support</module>
    <module>test/integration-test</module>
    <module>test/coverage-aggregate</module>
    <module>docker-build-config</module>
  </modules>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.3.13</version>
    <relativePath/>
  </parent>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <java.version>17</java.version>
    <spring-cloud.version>2023.0.5</spring-cloud.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.servicecomb.poc.demo</groupId>
        <artifactId>seckill-event-store</artifactId>
        <version>0.2.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>io.servicecomb.poc.demo</groupId>
        <artifactId>seckill-command-service</artifactId>
        <version>0.2.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>io.servicecomb.poc.demo</groupId>
        <artifactId>seckill-persist-service</artifactId>
        <version>0.2.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>io.servicecomb.poc.demo</groupId>
        <artifactId>seckill-admin-service</artifactId>
        <version>0.2.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>io.servicecomb.poc.demo</groupId>
        <artifactId>seckill-query-service</artifactId>
        <version>0.2.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>io.servicecomb.poc.demo</groupId>
        <artifactId>seckill-event-service</artifactId>
        <version>0.2.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>io.servicecomb.poc.demo</groupId>
        <artifactId>seckill-gateway</artifactId>
        <version>0.2.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring-cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>io.servicecomb.poc.demo</groupId>
        <artifactId>test-support</artifactId>
        <version>0.2.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>io.servicecomb.poc.demo</groupId>
        <artifactId>seckill-infra-redis</artifactId>
        <version>0.2.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>io.servicecomb.poc.demo</groupId>
        <artifactId>seckill-infra-kafka</artifactId>
        <version>0.2.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>io.servicecomb.poc.demo</groupId>
        <artifactId>seckill-infra-es</artifactId>
        <version>0.2.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>redis.clients</groupId>
        <artifactId>jedis</artifactId>
        <version>5.1.5</version>
        <exclusions>
          <exclusion>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
      <dependency>
        <groupId>org.awaitility</groupId>
        <artifactId>awaitility</artifactId>
        <version>4.2.2</version>
        <scope>test</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.commonjava.maven.plugins</groupId>
          <artifactId>directory-maven-plugin</artifactId>
          <version>1.0</version>
        </plugin>
        <plugin>
          <groupId>io.fabric8</groupId>
          <artifactId>docker-maven-plugin</artifactId>
          <version>0.45.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <configuration>
            <reuseForks>false</reuseForks>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.eluder.coveralls</groupId>
          <artifactId>coveralls-maven-plugin</artifactId>
          <version>4.3.0</version>
          <configuration>
            <jacocoReports>
              <jacocoReport>
                ${maven.multiModuleProjectDirectory}/test/coverage-aggregate/target/site/jacoco-aggregate/jacoco.xml
              </jacocoReport>
            </jacocoReports>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.jacoco</groupId>
          <artifactId>jacoco-maven-plugin</artifactId>
          <version>0.8.12</version>
          <configuration>
            <excludes>
              <exclude>**/*io/servicecomb/poc/demo/seckill/BadRequestExceptionAdvice.class</exclude>
              <exclude>**/*io/servicecomb/poc/demo/seckill/InvocationExceptionHandlerExceptionResolver.class</exclude>
              <exclude>**/*io/servicecomb/poc/demo/seckill/TooManyRequestsExceptionAdvice.class</exclude>
            </excludes>
          </configuration>
          <executions>
            <execution>
              <id>default-prepare-agent</id>
              <goals>
                <goal>prepare-agent</goal>
              </goals>
              <configuration>
                <destFile>${project.build.directory}/jacoco.exec</destFile>
              </configuration>
            </execution>
            <execution>
              <id>default-prepare-agent-integration</id>
              <phase>pre-integration-test</phase>
              <goals>
                <goal>prepare-agent-integration</goal>
              </goals>
              <configuration>
                <destFile>${project.build.directory}/jacoco-it.exec</destFile>
                <propertyName>jacoco.failsafe.argLine</propertyName>
              </configuration>
            </execution>
            <execution>
              <id>default-report</id>
              <goals>
                <goal>report</goal>
              </goals>
            </execution>
            <execution>
              <id>default-report-integration</id>
              <goals>
                <goal>report-integration</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

  <profiles>
    <profile>
      <id>docker-machine</id>
      <build>
        <pluginManagement>
          <plugins>
            <plugin>
              <groupId>io.fabric8</groupId>
              <artifactId>docker-maven-plugin</artifactId>
              <configuration>
                <machine>
                  <name>default</name>
                  <autoCreate>true</autoCreate>
                </machine>
              </configuration>
            </plugin>
          </plugins>
        </pluginManagement>
      </build>
    </profile>
    <profile>
      <id>jacoco</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.jacoco</groupId>
            <artifactId>jacoco-maven-plugin</artifactId>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
