server.port=8085
spring.application.name=seckill-gateway
management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health
management.health.redis.enabled=true

seckill.gateway.rate-limiter=redis
seckill.gateway.redis-host=redis.servicecomb.io
seckill.gateway.redis-port=6379
seckill.gateway.admin-uri=http://admin-service:8081
seckill.gateway.command-uri=http://command-service:8082
seckill.gateway.query-uri=http://query-service:8083
