server.port=8085
spring.application.name=seckill-gateway
management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health
management.health.redis.enabled=false

seckill.gateway.rate-limiter=memory
seckill.gateway.admin-uri=http://localhost:8081
seckill.gateway.command-uri=http://localhost:8082
seckill.gateway.query-uri=http://localhost:8083
seckill.gateway.admin.replenish-rate=10
seckill.gateway.admin.burst-capacity=20
seckill.gateway.command.replenish-rate=50
seckill.gateway.command.burst-capacity=100
seckill.gateway.query.replenish-rate=100
seckill.gateway.query.burst-capacity=200

spring.cloud.gateway.httpclient.connect-timeout=1000
spring.cloud.gateway.httpclient.response-timeout=3s

resilience4j.timelimiter.instances.adminCb.timeoutDuration=2s
resilience4j.timelimiter.instances.commandCb.timeoutDuration=800ms
resilience4j.timelimiter.instances.queryCb.timeoutDuration=2s

resilience4j.circuitbreaker.instances.adminCb.slidingWindowSize=20
resilience4j.circuitbreaker.instances.adminCb.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.adminCb.failureRateThreshold=50
resilience4j.circuitbreaker.instances.adminCb.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.adminCb.permittedNumberOfCallsInHalfOpenState=3

resilience4j.circuitbreaker.instances.commandCb.slidingWindowSize=20
resilience4j.circuitbreaker.instances.commandCb.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.commandCb.failureRateThreshold=50
resilience4j.circuitbreaker.instances.commandCb.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.commandCb.permittedNumberOfCallsInHalfOpenState=3

resilience4j.circuitbreaker.instances.queryCb.slidingWindowSize=20
resilience4j.circuitbreaker.instances.queryCb.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.queryCb.failureRateThreshold=50
resilience4j.circuitbreaker.instances.queryCb.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.queryCb.permittedNumberOfCallsInHalfOpenState=3
