server.port=8084
spring.datasource.url=jdbc:postgresql://postgres.servicecomb.io:5432/seckill
spring.datasource.username=seckill
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL9Dialect
seckill.infra.mode=prod
seckill.redis.host=redis.servicecomb.io
seckill.redis.port=6379
seckill.kafka.bootstrap=kafka.servicecomb.io:9092
seckill.es.url=http://es.servicecomb.io:9200
