apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: seckill
spec:
  selector:
    app: admin-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: seckill
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "5432,6379,9092,9200"
    spec:
      containers:
        - name: admin
          image: seckill-admin-service:0.2.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_OPTS
              value: >-
                -Dspring.profiles.active=prd
                -Dspring.datasource.url=jdbc:postgresql://postgres:5432/seckill
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 5
