server.port=8087
spring.datasource.url=jdbc:postgresql://postgres.servicecomb.io:5432/seckill
spring.datasource.username=seckill
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health
seckill.infra.mode=prod
seckill.kafka.bootstrap=kafka.servicecomb.io:9092
seckill.outbox.cdc.enabled=true
